---
name: Microsoft Defender For DevOps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 25 5 * * 4  # Every Thursday at 5:25 UTC

permissions:
  security-events: write
  contents: read

jobs:
  MSDO:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET (optional if not scanning .NET code)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x

      - name: Run Microsoft Security DevOps scan
        uses: microsoft/security-devops-action@v1.6.0
        id: msdo
        with:
          configFile: msdo.json

      - name: Upload SARIF results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
