name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ~/.buildx-cache
          key: docker-${{ github.sha }}
          restore-keys: |
            docker-

      - name: Pre-build memory usage
        run: |
          echo "=== Before build ==="
          free -h
          df -h

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: my-image-name:ci
          cache-from: type=local,src=~/.buildx-cache
          cache-to: type=local,dest=~/.buildx-cache,new=true
          push: false

      - name: Post-build memory usage
        run: |
          echo "=== After build ==="
          free -h
          df -h
          docker system df

      - name: Cleanup Docker
        if: always()
        run: |
          docker system prune -af
          docker volume prune -f
